[project]
name = "t4wefan-tomldb"
version = "0.1.7"
description = "A simple db using toml and pickle and dill."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dill",
    "filelock",
    "setuptools",
    "toml",
]

[dependency-groups]
dev = [
    "pillow>=11.1.0",
]
